Repository opennaslab/kubespider, pull requests merged in 2024-03, with the labels that each got.

#471 doc: update doc
  docs/zh/user_guide/ani_source_provider/README.md
Labels: documentation

#473 feat: plugin api add up status
  kubespider/api/v2/plugin/views.py
  kubespider/core/plugin_manager.py
  sdk/example/Dockerfile
Labels: enhancement

#474 doc: add plugin yaml definition
  docs/zh/contribute/plugin_definition.md
Labels: documentation

#476 add bilibili short url support
  kubespider/source_provider/bilibili_source_provider/provider.py
Labels: enhancement

#479 update:update plugin definition
  docs/zh/contribute/plugin_definition.md
Labels: enhancement

#480 fix: yutto downloader not recognize url from app
  kubespider/download_provider/yutto_download_provider/provider.py
  kubespider/source_provider/bilibili_source_provider/provider.py
Labels: bug

#484 doc: update main readme guide with unraid installation
  README-CN.md
  README.md
Labels: documentation

#486 fix: yutto downloader docker image does not read sessdata config under short link
  downloaders/yutto/app/core/tasks.py
Labels: bug

#488 doc: make majic source provider guidance better
  docs/zh/user_guide/magic_source_provider/README.md
Labels: documentation

#490 fix: Added check for existence of URLs in event source
  kubespider/source_provider/bilibili_source_provider/provider.py
Labels: bug

#492 feat: Improve dataSource retrieval logic
  kubespider-extension/src/background/index.ts
Labels: enhancement

#495 chore: bump yutto version to `2.0.0-beta.37` and fix typo in code
  downloaders/yutto/app/core/tasks.py
  downloaders/yutto/requirements.txt
Labels: dependencies
